import findPark from './findPark';
import viewPark from './viewPark';
import Payments from './payments';
import visitedParks from './visitedParks';
import BookingRequest from './bookingRequest';
import QrCode from './Qrcode';
import timer from './timer';
import payment from './payment';
export {findPark,viewPark, Payments, visitedParks,BookingRequest,QrCode,timer,payment};
